board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    path('commonboard/', views.IndexView.as_view(), name='commonboard_list'),
    path('commonboard/<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('세종대학교/', views.IndexViewP1.as_view(), name='privateboard1_list'),
    path('세종대학교/<int:pk>/', views.DetailViewP1.as_view(), name='p1_detail'),
    path('SSG대학교/', views.IndexViewP2.as_view(), name='privateboard2_list'),
    path('SSG대학교/<int:pk>/', views.DetailViewP2.as_view(), name='p2_detail'),
    path('commonboard/create', views.commonboard_create, name='commonboard_create'),
    path('index/',views.index, name='index'),
]

ctf_csrf문제/urls.py
from django.contrib import admin
from django.urls import path, include
from board import views
import users.views

urlpatterns = [
    path('ssgsamdinadmin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
    path('board/', include('board.urls')),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

board/models.py
# notice/models.py

import os
from django.conf import settings
from django.db import models
from users.models import User
import datetime

class CommonBoard(models.Model): #공통 게시판
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.CharField(max_length=256, verbose_name='내용')
    create_date = models.DateTimeField(null=True, blank=False)

class PrivateBoard1(models.Model): #비밀1 게시판
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.CharField(max_length=128, verbose_name='제목')
    create_date = models.DateTimeField(null=True, blank=False)

class PrivateBoard2(models.Model): #공통 게시판
    writer = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True, verbose_name='작성자')
    title = models.CharField(max_length=128, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    create_date = models.DateTimeField(null=True, blank=False)

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    nickname = models.CharField(max_length=50)

board/forms.py
from django import forms
from board.models import CommonBoard


class CommonBoardForm(forms.ModelForm):
    class Meta:
        model = CommonBoard  # 사용할 모델
        fields = ['title', 'content']

users/forms.py
from django import forms
from users.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import Group


class CsRegisterForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

    def save(self, commit=True):
        user = super(CsRegisterForm, self).save(commit=False)
        user.save()
        group = Group.objects.get(name='세종대학교')
        user.groups.add(group)
        return user

board/views.py
from django.http import HttpResponse
from django.views.generic import ListView, DetailView
from .models import CommonBoard, PrivateBoard1, PrivateBoard2
from .forms import CommonBoardForm
from django.shortcuts import render, redirect
from django.utils import timezone
from users.decorators import login_message_required, check_user_able_to_see_page1, check_user_able_to_see_page2
from django.contrib.auth.decorators import permission_required
from django.utils.decorators import method_decorator
from users.models import User

def index(request):
    return render(request, 'board/index.html')

@method_decorator(login_message_required,name='dispatch')
class IndexView(ListView):# 공통 게시판
    def get_queryset(self):
        if self.request.user.groups.filter(name="세종대학교").exists(): # 세종대 즉 참가자의 경우 자신의 글만 보이도록함
            mypost = CommonBoard.objects.filter(writer=self.request.user)
            return mypost.order_by('-create_date')
        else: #참가자가 아닌경우 (ssg 크롤러)는 모든글을 볼 수 있도록함
            return CommonBoard.objects.order_by('-create_date')

@method_decorator(login_message_required,name='dispatch')
class DetailView(DetailView):
    model = CommonBoard
    def get(self, request, *args, **kwargs): # 자기글만 확인 가능
        if self.request.user.groups.filter(name="세종대학교").exists():
            self.object = self.get_object(queryset=CommonBoard.objects.filter(writer=self.request.user))
        return super().get(request, *args, **kwargs)

@method_decorator(check_user_able_to_see_page1, name='dispatch')
class IndexViewP1(ListView):#비밀 게시판1
    def get_queryset(self):
        return PrivateBoard1.objects.order_by('-create_date')

@method_decorator(check_user_able_to_see_page1, name='dispatch')
class DetailViewP1(DetailView):
    model = PrivateBoard1


@method_decorator(check_user_able_to_see_page2, name='dispatch')
class IndexViewP2(ListView):#비밀 게시판2
    def get_queryset(self):
        return PrivateBoard2.objects.order_by('-create_date')

@method_decorator(check_user_able_to_see_page2, name='dispatch')
class DetailViewP2(DetailView):
    model = PrivateBoard2

@login_message_required
def commonboard_create(request):
    if request.method == 'POST':
        form = CommonBoardForm(request.POST)
        if form.is_valid():
            commonboard = form.save(commit=False)
            commonboard.create_date = timezone.now()
            commonboard.writer = request.user
            commonboard.save()
            return redirect('board:commonboard_list')
    else:
        form = CommonBoardForm()
    context = {'form': form}
    return render(request, 'board/commonboard_form.html', context)

users/views.py
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from users.forms import CsRegisterForm
from django.views.generic import CreateView


# Create your views here.
def register(request):
    if request.method == "POST":
        form = CsRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('/board/index/')
    else:
        form = CsRegisterForm
    return render(request, 'users/register.html', {'form': form})

templates/base.html
{% load static %}
{% load board_extras %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <div class="alert {{ message.tags }} alert-auto-dismissible alert-dismissible notification-container text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
        {{ message }}
    </div>
{% endfor %}
{% endif %}

<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Every Sejong</title>
</head>
<body>
<!-- 네비게이션바 -->
{% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
</body>
</html>

templates/board/commonboard_detail.html
{% extends 'base.html' %}
{% load board_extras %}
{% block content %}
{% autoescape off %}
<div class="container my-3">
    <!-- 글 -->
    <h2 class="border-bottom py-2">{{ commonboard.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ commonboard|protect_xss|safe|escape}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ commonboard.create_date }}
                </div>
            </div>
        </div>
    </div>
{% endautoescape %}
</div>
{% endblock %}

templates/board/commonboard_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">글등록</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/board/commonboard_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <p>공통게시판</p>
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if commonboard_list %}
        {% for commonboard in commonboard_list %}
        <tr class="list1">
            <td class="num">{{ commonboard.id }}</td>
            <td>
                <a href="{% url 'board:detail' commonboard.id %}">{{ commonboard.title }}</a>
            </td>
            <td>{{ commonboard.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>


            <td colspan="3">등록된 글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
    <a href="{% url 'board:commonboard_create' %}" class="btn btn-primary">글쓰기</a>
</div>
{% endblock %}

templates/board/index.html
{% extends "base.html" %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<body>
</body>
</html>

templates/board/privateboard1_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 글 -->
    <h2 class="border-bottom py-2">{{ privateboard1.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ privateboard1.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ privateboard1.create_date }}
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/board/privateboard1_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if privateboard1_list %}
        {% for privateboard1 in privateboard1_list %}
        <tr>
            <td>{{ privateboard1.id }}</td>
            <td>
                <a href="{% url 'board:p1_detail' privateboard1.id %}">{{ privateboard1.title }}</a>
            </td>
            <td>{{ privateboard1.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/board/privateboard2_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <!-- 글 -->
    <h2 class="border-bottom py-2">{{ privateboard2.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ privateboard2.content}}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ privateboard2.create_date }}
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

templates/board/privateboard2_list.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <table class="table">
        <thead>
        <tr class="table-dark">
            <th>번호</th>
            <th>제목</th>
            <th>작성일시</th>
        </tr>
        </thead>
        <tbody>
        {% if privateboard2_list %}
        {% for privateboard2 in privateboard2_list %}
        <tr>
            <td>{{ privateboard2.id }}</td>
            <td>
                <a href="{% url 'board:p2_detail' privateboard2.id %}">{{ privateboard2.title }}</a>
            </td>
            <td>{{ privateboard2.create_date }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">등록된 글이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>
</div>
{% endblock %}

templates/form_errors.html
<!-- 필드 오류와 넌필드 오류를 출력한다. -->
{% if form.errors %}
<div class="alert alert-danger">
    {% for field in form %}
    <!-- 필드 오류 -->
    {% if field.errors %}
    <div>
        <strong>{{ field.label }}</strong>
        {{ field.errors }}
    </div>
    {% endif %}
    {% endfor %}
    <!-- 넌필드 오류 -->
    {% for error in form.non_field_errors %}
    <div>
        <strong>{{ error }}</strong>
    </div>
    {% endfor %}
</div>
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
{% load board_extras %}
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">Home</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                    {% if not user|has_group:"SSG대학교" %}
                            <a class="nav-link" href="{% url 'users:logout' %}">{{ user.username }} (로그아웃)</a>
                        {% endif %} 
                     <a class="nav-link" href="{% url 'board:commonboard_list' %}">공통게시판</a>
                        {% if user|has_group:"SSG대학교" %}
                            <a class="nav-link" href="{% url 'board:privateboard2_list' %}">학교게시판</a>
                        {% else %}
                            <a class="nav-link" href="{% url 'board:privateboard1_list' %}">학교게시판</a>
                        {% endif %}
                    {% else %}
                    <a class="nav-link" href="{% url 'users:login' %}">로그인</a>
                    <a class="nav-link" href="{% url 'users:register' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/users/login.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자ID</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password">비밀번호</label>
            <input type="password" class="form-control" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">로그인</button>
    </form>
</div>
{% endblock %}

templates/users/register.html
{% extends "base.html" %}
{% block content %}
<div class="container my-3">
    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="mb-3">
            <label for="username">사용자 이름</label>
            <input type="text" class="form-control" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password1">비밀번호</label>
            <input type="password" class="form-control" name="password1" id="password1"
                   value="{{ form.password1.value|default_if_none:'' }}">
        </div>
        <div class="mb-3">
            <label for="password2">비밀번호 확인</label>
            <input type="password" class="form-control" name="password2" id="password2"
                   value="{{ form.password2.value|default_if_none:'' }}">
        </div>
        <button type="submit" class="btn btn-primary">생성하기</button>
    </form>
</div>
{% endblock %}

templates/users/user_base.html
<!-- templates/users/user_base.html -->

<html>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    {% block header %}
    <!-- header 삽입 부분 -->
    {% endblock %}
</head>

<body style="background-color: #d6d6d6;">
    {% block contents %}
    <!-- body 삽입 부분 -->
    {% endblock %}

    {% if messages %}
    {% for message in messages %}
    {% if message.tags %}
    <script>
        alert("{{ message.message }}") <!-- message alert script -->
    </script>
    {% endif %}
    {% endfor %}
    {% endif %}
</body>

</html>